### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by dthree** [AljoschaMeyer/metronome-cli#2]
It's probably really hard to do tests for this, but perhaps you could implement some basic coverage tests.

I really like this to be on the awesome list, as it's a great example of how creative you can get with Vorpal, but I do want everything on the list to be test-passing.

Thanks! :+1:

**Comment by AljoschaMeyer** [comment]
That is why I didn't do a PR on the list for it =P

The parts that took some thinking, trial and error were audio-related, i.e how do I get silence between the beats. I really don't know how to test this stuff. The difficult part is not to verify that the metronome tone generator uses  `(time % (60 / controls.bpm)) > controls.length` to determine when to output silence, but to get to that formula.

Tapping for bpm thankfully is another module.

Everything else is very basic. I'm currently rewriting it to use setorprint, and there won't be a lot to test left afterwards, since setorprint itself is tested.

That leaves turning the metronome on and off, the event handlers for keyboard control, and the catch method which allows setting the bpm without a command. I guess I can write tests for these. Then again, I already put more time into this then I anticipated. But if you give me a few days, I'll get it done...

I'm surprised this turned out to be pretty useful, so in the long run I'll likely be happy I added the tests.

**Comment by dthree** [comment]
Haha yeah . I got excited.

No probs :)

**Comment by AljoschaMeyer** [comment]
I'll do the setorprint-rewrite now, and then fully test this. However, I'm not motivated enough to figure out how to make travis accept the [speaker](https://www.npmjs.com/package/speaker) installation and handle sound. So no ci for this one.

**Comment by dthree** [comment]
Haha - k no biggie You don't need 100% coverage for CI btw, just some basic tests to make sure the code runs would be good.

**Comment by AljoschaMeyer** [comment]
I didn't get travis to go past installation, because the speaker install script fails.

I'll close this when the tests are done btw.

**Comment by dthree** [comment]
okay cool.

**Comment by AljoschaMeyer** [comment]
Honestly I just wanted to do the close-via-commitmessage-thing... :)

**Comment by dthree** [comment]
haha! Yes - it's very satisfying.
